"""Fix mixins field

Revision ID: be14d3a5cb0d
Revises: 81cf0eb6d41a
Create Date: 2024-07-14 09:20:54.221874
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'be14d3a5cb0d'
down_revision = '81cf0eb6d41a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.alter_column(
            'full_amount', existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            'invested_amount', existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            'fully_invested', existing_type=sa.BOOLEAN(), nullable=False
        )
        batch_op.alter_column(
            'create_date', existing_type=sa.DATETIME(), nullable=False
        )
        batch_op.alter_column(
            'name', existing_type=sa.VARCHAR(length=100), nullable=False
        )
        batch_op.alter_column(
            'description', existing_type=sa.TEXT(), nullable=False
        )
        batch_op.create_unique_constraint('unique_name', ['name'])

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column(
            'full_amount', existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            'invested_amount', existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            'fully_invested', existing_type=sa.BOOLEAN(), nullable=False
        )
        batch_op.alter_column(
            'create_date', existing_type=sa.DATETIME(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column(
            'create_date', existing_type=sa.DATETIME(), nullable=True
        )
        batch_op.alter_column(
            'fully_invested', existing_type=sa.BOOLEAN(), nullable=True
        )
        batch_op.alter_column(
            'invested_amount', existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            'full_amount', existing_type=sa.INTEGER(), nullable=True
        )

    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column(
            'description', existing_type=sa.TEXT(), nullable=True
        )
        batch_op.alter_column(
            'name', existing_type=sa.VARCHAR(length=100), nullable=True
        )
        batch_op.alter_column(
            'create_date', existing_type=sa.DATETIME(), nullable=True
        )
        batch_op.alter_column(
            'fully_invested', existing_type=sa.BOOLEAN(), nullable=True
        )
        batch_op.alter_column(
            'invested_amount', existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            'full_amount', existing_type=sa.INTEGER(), nullable=True
        )

    # ### end Alembic commands ###
